[build]
  publish = "backend/static"

[[redirects]]
  from = "/*"
  to = "https://disease-prediction-nwnu.onrender.com/:splat"
  status = 302
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
